### ISSUE TITLE
Release feed

### ISSUE THREAD

**Issue by engram-design** [selvinortiz/craft.patrol#15]
It'd be great to have the plugin hooked up to a release feed to stay up to date with changes.

**Comment by selvinortiz** [comment]
Agreed! I'll try to get that in place as soon as I have a chance.

**Comment by engram-design** [comment]
No rush, just noticed it 😃  Thanks for the awesome plugin!

**Comment by selvinortiz** [comment]
@engram-design I quickly threw a `release.json` together and cut a release since I was already merging a PR from Matt Stein:) It only has a couple of entries right now but I don't think that should matter since the feed is not retroactive and you need to have the version of the plugin that knows about the release feed.
