### ISSUE TITLE
Does this create a canonical redirect?

### ISSUE THREAD

**Issue by jonlongnecker** [selvinortiz/craft.patrol#22]
Switching an existing site over to https and so far Patrol has made it way easier. I'm just wondering, though - is the redirect like a 301 .htaccess redirect or do I need to do something else to let search engines know that the pages have moved?

**Comment by selvinortiz** [comment]
Wow, I'm so sorry @jonlongnecker, I have no idea how I forgot to get back to you:( I remember getting the notification, just totally slipped my mind.

To answer your question (way late), Patrol does `302` to protect from issues that arise from accidentally using `301` as well as other best practices during development.

There is no setting/config to switch those from `302` to `301` but I can see how it could be useful.

How would this work, in your opinion? Maybe by having a `usePermanentRedirects` setting in the config file, or something along those lines?

**Comment by jonlongnecker** [comment]
Hah, apparently this is the slowest thread ever! So for me I used the plugin to force https for the whole site once I added an SSL. A site with like 10 years of content and pages. A switch in the admin area to make sure it's a true redirect (301) would be good I think - unless I'm using the plugin in a way it wasn't intended.

**Comment by selvinortiz** [comment]
@jonlongnecker I think the only reason this wasn't a feature from the start, was that when you're ready to take your site live, you'd probably want to handle that https redirect at the server level. You would use Patrol only for maintenance at that point.

So, I'd recommend adding https redirect rules in Apache or NginX if you have access to them.

**Comment by jonlongnecker** [comment]
I guess I don't really understand the point of forcing https if it's not for a live site then? Why even have the option if it's not for production?

**Comment by selvinortiz** [comment]
Because it helps during development (https on staging/production but not locally, etc) and because on some shared hosting environments, there is no easy way to manage https redirects easily.

Additionally, with Patrol, you can force https only on some sections of the site while forcing http on others if you want to minimize latency for example.

I should clarify that if you want to use Patrol in production, you can (that's why I'm considering the 301 feature) but if you have access to your server config (apache/nginx), that would be the canonical way of doing it for production.

**Comment by selvinortiz** [comment]
Moving this feature to Patrol for Craft 3
